# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
url:                "https://federicobianchi.io"
baseurl:             ""
permalink:           pretty

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Federico Bianchi'
description:	       'AI Engineer, ML Researcher'
author:              'Federico Bianchi'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
